#!/usr/bin/env node
/**
 * Bake TCGCSV market prices into prices.js for the static app.
 * Do not call TCGCSV from the browser.
 */
import { readFile, writeFile } from "node:fs/promises";

const TCGCSV = "https://tcgcsv.com/tcgplayer";
const CATEGORY = 89;
const UA = "BinderAtlas/1.0 (+https://github.com/atfox7/binder-atlas)";

async function getJson(url) {
  const response = await fetch(url, {
    headers: { Accept: "application/json", "User-Agent": UA }
  });
  if (!response.ok) throw new Error(`${response.status} ${response.statusText}: ${url}`);
  return response.json();
}

const snapshotText = await readFile(new URL("./cards-snapshot.js", import.meta.url), "utf8");
const snapMatch = snapshotText.match(/window\.RIFTBOUND_SNAPSHOT = (\{.*\});\s*$/s);
if (!snapMatch) throw new Error("cards-snapshot.js: snapshot JSON not found");
const snapshot = JSON.parse(snapMatch[1]);

const groupIds = [...new Set(snapshot.sets.map(set => set.tcgplayerGroupId).filter(Boolean))];
const byTcgplayerId = {};

for (const groupId of groupIds) {
  const data = await getJson(`${TCGCSV}/${CATEGORY}/${groupId}/prices`);
  const results = data.results || [];
  const byProduct = new Map();
  for (const row of results) {
    if (row.productId == null || row.marketPrice == null) continue;
    const list = byProduct.get(row.productId) || [];
    list.push(row);
    byProduct.set(row.productId, list);
  }
  for (const [productId, list] of byProduct) {
    const preferred =
      list.find(row => row.subTypeName === "Normal" && row.marketPrice != null) ||
      list.find(row => row.marketPrice != null);
    if (!preferred) continue;
    byTcgplayerId[String(productId)] = preferred.marketPrice;
  }
  process.stdout.write(`group ${groupId}: ${results.length} rows\n`);
}

const payload = {
  generatedAt: new Date().toISOString(),
  source: "tcgcsv.com category 89 (TCGPlayer Riftbound)",
  groups: groupIds,
  count: Object.keys(byTcgplayerId).length,
  byTcgplayerId
};

await writeFile(
  new URL("./prices.js", import.meta.url),
  `// Generated by bake-prices.mjs from TCGCSV. Do not edit by hand.\nwindow.RIFTBOUND_PRICES = ${JSON.stringify(payload)};\n`
);

process.stdout.write(`Wrote ${payload.count} market prices to prices.js\n`);
